name: Docker Image CI

on:
  push:
    tags: 
      - '**'

env:
  DOCKER_REPOSITORY: hoyeonyang
  CONTAINER_NAME: nest-hello-world


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Parse tags
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
    - name: Build the Docker image
      id: build-image
      env: 
        IMAGE_TAG: ${{ env.RELEASE_VERSION }}
      run: 
        docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$CONTAINER_NAME:$IMAGE_TAG
        echo "::set-output name=image_name::$DOCKER_REPOSITORY/$CONTAINER_NAME:$IMAGE_TAG"
      
    - name: Login to DockerHub
      uses: docker/login-action@v1                 
      with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
    
      
      
    - name: Push the Docker image
      run: docker push ${{ steps.build-image.outputs.image }}
