name: Docker Image CI

on:
  push:
    tags: 
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Parse tags
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
    - name: Build the Docker image
      env: 
        IMAGE_TAG: ${{ env.RELEASE_VERSION }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
